#!/bin/sh
linux(){
   apt update && apt upgrade && apt install ruby && apt install figlet && apt install python3.11 && gem install lolcat && pip install tqdm && clear && echo 'não apague esse arquivo' >> .config.txt
}
termux(){
   pkg update && pkg upgrade && pkg install ruby && pkg install figlet && pkg install python && gem install lolcat && pip install tqdm && clear && echo 'não apague esse arquivo' >> .config.txt
}

F="\033[m"
A="\033[01;33m"
VD="\033[01;32m"
clear 
echo $A"Qual seu SO?"
echo $VD"["$A"1"$VD"]"$A"Linux"
echo $VD"["$A"2"$VD"]"$A"Termux"
echo -n $VD">>>"$F
read op
case $op in
	1)linux;;
	2)termux;;
	*)clear;exit;;
esac
